language: ruby
sudo: false
rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - jruby-1.7.25
  - jruby-9.0.5.0
  - jruby-9.1.2.0
  - jruby-head
  - rbx
  - rbx-2
before_install:
  - gem query -i -n ^bundler$ > /dev/null || gem install --no-ri --no-rdoc bundler
notifications:
  email:
    - uwe@kubosch.no
