module Gruff
  class Renderer::Dot
    @renderer: Renderer
    @style: Symbol
    @color: String
    @width: Float
    @opacity: Float

    def initialize: (Renderer renderer, interned style, color: String, ?width: Float, ?opacity: Float) -> void
    def render: (Float new_x, Float new_y, Float radius) -> void

  private

    def circle: (Float new_x, Float new_y, Float radius) -> void
    def square: (Float new_x, Float new_y, Float radius) -> void
    def diamond: (Float new_x, Float new_y, Float radius) -> void
  end
end
