#
# Here's how to set up a Gruff::Histogram.
#
#   g = Gruff::Histogram.new
#   g.title = 'Histogram Graph'
#   g.minimum_bin = 10
#   g.bin_width = 20
#   g.data :A, [10, 10, 20, 30, 40, 40, 40, 40, 40, 40, 50, 10, 10, 10]
#   g.data :B, [100, 100, 100, 100, 90, 90, 80, 30, 30, 30, 30, 30]
#   g.write('histogram.png')
#
class Gruff::Histogram < Gruff::Bar
  @data: untyped

  @bin_width: untyped

  @minimum_bin: untyped

  @maximum_bin: untyped

  # Specifies interpolation between the min and max of the set. Default is +10+.
  attr_writer bin_width: untyped

  # Specifies minimum value for bin.
  attr_writer minimum_bin: untyped

  # Specifies maximum value for bin.
  attr_writer maximum_bin: untyped

  def initialize: (*untyped) -> void

  def data: (untyped name, ?untyped data_points, ?untyped? color) -> untyped

  private

  def initialize_attributes: () -> untyped

  def setup_data: () -> untyped

  # @private
  class HistogramArray < Array[Integer | Float]
    # include ::Histogram
  end
end
